### ISSUE TITLE
Docker Container does not work with Swift 4.2

### ISSUE THREAD

**Issue by halilyilmaz** [vapor-community/docker#10]
Trying to run the docker container it does not work.

swift build -c release
warning: unable to restore checkouts state: unexpectedData
error: Package requires minimum Swift tools version 4.2.0. Current Swift tools version is 3.1.0

**Comment by vzsg** [comment]
You should not use this repository or any mentioned images within anymore, as it's superseded by the official Swift images.

Check out [these guides](https://bygri.github.io/) instead 👍
