### ISSUE TITLE
I cannot get this to work

### ISSUE THREAD

**Issue by larsoleruben** [vapor-community/docker#8]
Hi

I eventually found the problem. Since Vapor 3, the hostname is not defaulted to 0.0.0.0 anymore, so you have to start the webserver with the parameter --hostname 0.0.0.0 and then it works.
It should be possible to add this by default in the config file?
Or you should make people aware of it!

I can run nginx containers and easily connect to the webserver. I have also other containers running fine.
But this does not work. I have tried the vapor image and also to make my own. if I log in to the container, the webserver is running fine, and I can call it with curl.
But even though I have opened port 8080 and also exposed it, the webserver then responds with and empty answer?
I have attacehed the build files.
[Dockerfile.txt](https://github.com/vapor-community/docker/files/1999064/Dockerfile.txt)

FROM ubuntu:16.04

LABEL maintainer="zyxep"

# Install CURL
RUN apt-get update && \
    apt-get -y install curl && \
    rm -rf /var/lib/apt/lists/*;

# Get Vapor repo including Swift
RUN curl -sL https://apt.vapor.sh | bash;

# Installing Swift & Vapor
RUN apt-get update && \
    apt-get -y install swift vapor && \
    rm -rf /var/lib/apt/lists/*;

WORKDIR /vapor
RUN vapor new web
WORKDIR /vapor/web
RUN vapor build
EXPOSE 8080
CMD ["vapor", "run"]

**Comment by vzsg** [comment]
This repo is deprecated as there are more streamlined alternatives (see the link in the README).

---

To answer the question, you should be able to add `"--hostname", "0.0.0.0"` to the last CMD line, or have a custom NIOServerConfig in your application code. If this, or the guide doesn't help, feel free to join the [Vapor discord server](https://discord.gg/vapor) and ask around.
